site_name: 「寻寰」设定站
site_url: https://blog.uchout.moe/xunhuan-doc/
site_description: >-
  「寻寰」游戏设定站，为了更好的开发游戏而设定。

theme:
  name: material
  language: zh
  features:
   - header.autohide
   - navigation.tracking
   - navigation.top
   - search.highlight
   - search.share
   - search.suggest
   - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Ubuntu

repo_url: https://github.com/uchouT/xunhuan-doc


nav:
  - 主页: index.md
  - 游戏设定: 
      - 世界观: game/lore.md
      - 角色介绍: game/characters.md
      - 怪物: game/monsters.md
  - 开发:
      - 属性整理: dev/初步构想.md
      

